```{r}
install.packages("renv")
renv::init()
renv::status()
```

```{r}
install.packages("tidyverse")
library(tidyverse)

install.packages("palmerpenguins")
library(palmerpenguins)
data(package = 'palmerpenguins')
```

```{r}
# HANDLING MISSING VALUES
sum(is.na(penguins)) #check for missing data
penguins <- na.omit(penguins) #omit missing data from the original dataset
```

```{r}
# VISUALIZATION
ggplot(penguins, aes(x = body_mass_g)) + 
  geom_histogram(bins = 30, fill = "blue", color = "white")

ggplot(penguins, aes(x = species, y = flipper_length_mm, fill = species)) + 
  geom_boxplot()

ggplot(penguins, aes(x = bill_length_mm, y = bill_depth_mm, color = species)) + 
  geom_point()
```

```{r}
# SUMMARY STATISTICS
penguins %>% 
  group_by(species) %>% 
  summarise(across(c(bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g), mean, na.rm = TRUE))
```

```{r}
# CORRELATION ANALYSIS
cor_penguins <- select(penguins, bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g)
cor(cor_penguins, use = "complete.obs")
```

```{r}
## LAB 3

con <- DBI::dbConnect(duckdb::duckdb(), dbdir = "my-db.duckdb")

# Optionally check if the table exists and then decide to overwrite or append
if (DBI::dbExistsTable(con, "penguins")) {
    DBI::dbWriteTable(con, "penguins", palmerpenguins::penguins, overwrite = TRUE)
} else {
    DBI::dbWriteTable(con, "penguins", palmerpenguins::penguins)
}

DBI::dbDisconnect(con)

```

```{r}
renv::snapshot()
```
